INSERT INTO changas(changa_id, user_id, street, neighborhood, number, creation_date, title, description, state, price)
VALUES (1, 5, 'calle1', 'San Telmo', 1, null, 'Se busca nene de 5 años', 'Vigorosooo', 'settled', 123),
       (2, 3, 'calle3', 'San Isidro', 13123, null, 'Se busca nene de 5 años', 'Vigorosooo', 'settled', 312),
       (3, 3, 'calle2', 'San Telmo', 231, null, 'Lavar el perro', 'Dale candela', 'done', 1),
       (4, 5, 'calle4', 'San Isidro', 231, null, 'Lavarme el culo', 'Vigorosooo', 'settled', 312),
       (5, 2, 'calle5', 'San Isidro', 231, null, 'Se busca nene de 5 años', 'Vigorosooo', 'settled', 312),
       (6, 5, 'calle1', 'Juarez', 231, null, 'Lavarme el culo', 'Vigorosooo', 'emitted', 123),
       (7, 5, 'calle2', 'San Telmo', 312, null, 'Prositushon', 'Full energetic', 'done', 1),
       (8, 2, 'calle3', 'San Fer', 1, null, 'Lavar el perro', 'Dale candela', 'emitted', 123),
       (9, 1, 'calle3', 'San Telmo', 231, null, 'Prositushon', 'Full energetic', 'closed', 123),
       (10, 1, 'calle2', 'San Isidro', 231, null, 'Lavar los platos', 'Vigorosooo', 'settled', 13123),
       (11, 1, 'calle5', 'San Telmo', 123, null, 'Lavar los platos', 'Hay que hacerlo la palo', 'closed', 312),
       (12, 5, 'calle3', 'San Telmo', 123, null, 'Lavar el perro', 'Full energetic', 'closed', 13123),
       (13, 3, 'calle5', 'San Isidro', 312, null, 'Lavar los platos', 'Hay que hacerlo la palo', 'done', 123),
       (14, 1, 'calle1', 'San Telmo', 123, null, 'Lavarme el culo', 'Muevete', 'closed', 1),
       (15, 5, 'calle5', 'Juarez', 1, null, 'Lavarme el culo', 'Hay que hacerlo la palo', 'settled', 231),
       (16, 2, 'calle4', 'San Telmo', 312, null, 'Lavar el perro', 'Vigorosooo', 'done', 13123),
       (17, 1, 'calle1', 'San Isidro', 13123, null, 'Se busca nene de 5 años', 'Dale candela', 'emitted', 1),
       (18, 3, 'calle1', 'San Isidro', 13123, null, 'Lavar el perro', 'Vigorosooo', 'closed', 231),
       (19, 2, 'calle4', 'San Fer', 123, null, 'Lavar los platos', 'Muevete', 'settled', 123),
       (20, 2, 'calle1', 'San Fer', 1, null, 'Lavar los platos', 'Hay que hacerlo la palo', 'settled', 231),
       (21, 1, 'calle1', 'San Fer', 123, null, 'Lavar el perro', 'Full energetic', 'settled', 1),
       (22, 2, 'calle3', 'San Fer', 123, null, 'Lavarme el culo', 'Muevete', 'settled', 1),
       (23, 4, 'calle2', 'Martinez', 123, null, 'Prositushon', 'Muevete', 'closed', 312),
       (24, 2, 'calle2', 'Martinez', 1, null, 'Lavar el perro', 'Full energetic', 'emitted', 312),
       (25, 2, 'calle4', 'San Fer', 123, null, 'Prositushon', 'Vigorosooo', 'closed', 13123),
       (26, 2, 'calle5', 'Juarez', 13123, null, 'Lavarme el culo', 'Full energetic', 'settled', 1),
       (27, 3, 'calle2', 'San Telmo', 13123, null, 'Lavar el perro', 'Hay que hacerlo la palo', 'done', 1),
       (28, 5, 'calle1', 'San Telmo', 1, null, 'Se busca nene de 5 años', 'Muevete', 'settled', 1),
       (29, 4, 'calle3', 'San Fer', 231, null, 'Se busca nene de 5 años', 'Muevete', 'settled', 231),
       (30, 2, 'calle1', 'San Fer', 13123, null, 'Lavar los platos', 'Full energetic', 'closed', 1),
       (31, 2, 'calle1', 'San Isidro', 231, null, 'Lavarme el culo', 'Dale candela', 'emitted', 123),
       (32, 1, 'calle1', 'San Telmo', 312, null, 'Se busca nene de 5 años', 'Dale candela', 'settled', 123),
       (33, 1, 'calle5', 'Juarez', 13123, null, 'Lavar los platos', 'Vigorosooo', 'settled', 123),
       (34, 5, 'calle2', 'Juarez', 1, null, 'Lavar los platos', 'Full energetic', 'settled', 13123),
       (35, 1, 'calle3', 'Juarez', 1, null, 'Lavar el perro', 'Hay que hacerlo la palo', 'emitted', 1),
       (36, 4, 'calle4', 'San Telmo', 312, null, 'Lavar los platos', 'Vigorosooo', 'closed', 13123),
       (37, 2, 'calle4', 'Martinez', 13123, null, 'Lavar el perro', 'Full energetic', 'settled', 123),
       (38, 3, 'calle3', 'Juarez', 123, null, 'Lavar los platos', 'Dale candela', 'closed', 123),
       (39, 5, 'calle5', 'Martinez', 231, null, 'Lavar los platos', 'Hay que hacerlo la palo', 'settled', 312),
       (40, 3, 'calle4', 'San Isidro', 231, null, 'Lavar el perro', 'Hay que hacerlo la palo', 'closed', 13123),
       (41, 4, 'calle4', 'San Isidro', 1, null, 'Lavarme el culo', 'Full energetic', 'settled', 13123),
       (42, 4, 'calle3', 'Juarez', 123, null, 'Se busca nene de 5 años', 'Dale candela', 'closed', 13123),
       (43, 1, 'calle3', 'San Telmo', 13123, null, 'Se busca nene de 5 años', 'Hay que hacerlo la palo', 'emitted', 231),
       (44, 1, 'calle4', 'San Telmo', 231, null, 'Prositushon', 'Vigorosooo', 'settled', 123),
       (45, 2, 'calle5', 'San Fer', 231, null, 'Prositushon', 'Muevete', 'emitted', 1),
       (46, 2, 'calle2', 'San Telmo', 1, null, 'Lavar el perro', 'Muevete', 'emitted', 13123),
       (47, 3, 'calle5', 'Martinez', 1, null, 'Prositushon', 'Dale candela', 'settled', 123),
       (48, 1, 'calle4', 'San Isidro', 1, null, 'Se busca nene de 5 años', 'Full energetic', 'settled', 13123),
       (49, 3, 'calle3', 'San Fer', 231, null, 'Se busca nene de 5 años', 'Muevete', 'settled', 13123),
       (50, 4, 'calle3', 'Juarez', 1, null, 'Lavar el perro', 'Dale candela', 'settled', 1),
       (51, 4, 'calle3', 'San Isidro', 123, null, 'Lavarme el culo', 'Hay que hacerlo la palo', 'settled', 13123),
       (52, 1, 'calle3', 'San Isidro', 13123, null, 'Se busca nene de 5 años', 'Hay que hacerlo la palo', 'emitted', 13123),
       (53, 2, 'calle1', 'San Fer', 13123, null, 'Lavarme el culo', 'Vigorosooo', 'settled', 312),
       (54, 1, 'calle4', 'San Telmo', 231, null, 'Lavar el perro', 'Hay que hacerlo la palo', 'done', 312),
       (55, 1, 'calle3', 'San Fer', 13123, null, 'Lavar los platos', 'Full energetic', 'settled', 13123),
       (56, 2, 'calle3', 'San Isidro', 312, null, 'Lavar los platos', 'Dale candela', 'settled', 231),
       (57, 1, 'calle4', 'San Fer', 123, null, 'Lavar los platos', 'Full energetic', 'settled', 312),
       (58, 3, 'calle5', 'San Isidro', 312, null, 'Lavar el perro', 'Dale candela', 'settled', 312),
       (59, 5, 'calle2', 'San Isidro', 1, null, 'Lavarme el culo', 'Muevete', 'closed', 13123),
       (60, 3, 'calle2', 'Martinez', 231, null, 'Lavar los platos', 'Full energetic', 'settled', 13123),
       (61, 4, 'calle5', 'San Telmo', 123, null, 'Prositushon', 'Hay que hacerlo la palo', 'done', 1),
       (62, 1, 'calle5', 'San Fer', 231, null, 'Lavar los platos', 'Muevete', 'emitted', 13123),
       (63, 1, 'calle4', 'Juarez', 123, null, 'Se busca nene de 5 años', 'Muevete', 'done', 312),
       (64, 5, 'calle3', 'San Isidro', 1, null, 'Lavar los platos', 'Full energetic', 'settled', 123),
       (65, 1, 'calle1', 'San Fer', 123, null, 'Lavar los platos', 'Full energetic', 'closed', 123),
       (66, 5, 'calle5', 'San Telmo', 13123, null, 'Lavar los platos', 'Hay que hacerlo la palo', 'settled', 1),
       (67, 5, 'calle2', 'San Isidro', 231, null, 'Lavar los platos', 'Vigorosooo', 'closed', 1),
       (68, 2, 'calle3', 'San Fer', 123, null, 'Lavar los platos', 'Vigorosooo', 'closed', 13123),
       (69, 5, 'calle2', 'Juarez', 231, null, 'Lavar el perro', 'Dale candela', 'closed', 123),
       (70, 5, 'calle4', 'San Isidro', 1, null, 'Lavar el perro', 'Hay que hacerlo la palo', 'done', 13123),
       (71, 5, 'calle1', 'San Telmo', 123, null, 'Lavar los platos', 'Dale candela', 'emitted', 231),
       (72, 5, 'calle5', 'Martinez', 1, null, 'Lavarme el culo', 'Vigorosooo', 'done', 1),
       (73, 5, 'calle4', 'San Isidro', 123, null, 'Prositushon', 'Vigorosooo', 'closed', 231),
       (74, 1, 'calle3', 'San Fer', 312, null, 'Lavarme el culo', 'Dale candela', 'settled', 1),
       (75, 3, 'calle3', 'San Telmo', 1, null, 'Lavar los platos', 'Full energetic', 'settled', 13123),
       (76, 4, 'calle5', 'San Isidro', 231, null, 'Lavarme el culo', 'Hay que hacerlo la palo', 'settled', 13123),
       (77, 5, 'calle3', 'Martinez', 231, null, 'Lavar el perro', 'Full energetic', 'done', 123),
       (78, 1, 'calle1', 'Juarez', 1, null, 'Lavar los platos', 'Full energetic', 'settled', 1),
       (79, 3, 'calle4', 'Juarez', 231, null, 'Se busca nene de 5 años', 'Hay que hacerlo la palo', 'emitted', 1),
       (80, 4, 'calle2', 'San Isidro', 312, null, 'Prositushon', 'Full energetic', 'emitted', 123),
       (81, 5, 'calle2', 'Juarez', 13123, null, 'Prositushon', 'Vigorosooo', 'done', 123),
       (82, 5, 'calle4', 'Juarez', 312, null, 'Prositushon', 'Full energetic', 'settled', 1),
       (83, 1, 'calle2', 'San Fer', 1, null, 'Lavarme el culo', 'Muevete', 'settled', 13123),
       (84, 1, 'calle3', 'San Fer', 231, null, 'Prositushon', 'Dale candela', 'emitted', 231),
       (85, 4, 'calle1', 'San Fer', 231, null, 'Lavarme el culo', 'Muevete', 'emitted', 13123),
       (86, 5, 'calle3', 'San Telmo', 13123, null, 'Lavarme el culo', 'Full energetic', 'settled', 1),
       (87, 5, 'calle1', 'Martinez', 123, null, 'Lavar el perro', 'Hay que hacerlo la palo', 'done', 312),
       (88, 5, 'calle2', 'San Fer', 1, null, 'Lavar los platos', 'Full energetic', 'done', 13123),
       (89, 5, 'calle4', 'San Fer', 231, null, 'Lavar los platos', 'Full energetic', 'closed', 231),
       (90, 5, 'calle1', 'San Fer', 312, null, 'Lavarme el culo', 'Dale candela', 'done', 231),
       (91, 1, 'calle1', 'San Telmo', 1, null, 'Prositushon', 'Hay que hacerlo la palo', 'settled', 231),
       (92, 3, 'calle5', 'San Fer', 13123, null, 'Lavar los platos', 'Hay que hacerlo la palo', 'emitted', 312),
       (93, 5, 'calle4', 'San Isidro', 123, null, 'Lavar los platos', 'Muevete', 'emitted', 231),
       (94, 5, 'calle2', 'San Isidro', 231, null, 'Lavarme el culo', 'Full energetic', 'done', 123),
       (95, 4, 'calle2', 'San Fer', 123, null, 'Lavar los platos', 'Full energetic', 'done', 231),
       (96, 1, 'calle4', 'Juarez', 231, null, 'Prositushon', 'Full energetic', 'closed', 231),
       (97, 3, 'calle1', 'San Fer', 123, null, 'Prositushon', 'Full energetic', 'emitted', 123),
       (98, 5, 'calle3', 'Juarez', 13123, null, 'Lavar el perro', 'Hay que hacerlo la palo', 'emitted', 13123),
       (99, 1, 'calle3', 'Martinez', 231, null, 'Prositushon', 'Dale candela', 'done', 1),
       (100, 5, 'calle4', 'San Isidro', 123, null, 'Lavar los platos', 'Dale candela', 'closed', 312)